name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
      env:
        CI: false
        
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'
      if: github.ref == 'refs/heads/main' && env.VERCEL_TOKEN != ''
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      
    - name: Vercel Setup Instructions
      if: github.ref == 'refs/heads/main' && env.VERCEL_TOKEN == ''
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        echo "⚠️  Vercel deployment skipped - secrets not configured"
        echo "To enable Vercel deployment, add these secrets to your GitHub repository:"
        echo "1. VERCEL_TOKEN - Your Vercel authentication token"
        echo "2. ORG_ID - Your Vercel organization ID"
        echo "3. PROJECT_ID - Your Vercel project ID"
        echo ""
        echo "Get these values from: https://vercel.com/account/tokens"